'use client';
import { useState, useRef, useEffect } from 'react';
import { useSearchParams } from 'next/navigation';
import GeneralInfo from './edit_areas/GeneralInfo';
import UploadPhotos from './edit_areas/UploadPhotos';
import PlaceChars from './edit_areas/PlaceChars';
import Social from './edit_areas/Social';
import PlaceDescription from './edit_areas/PlaceDescription';
import {
  GeneralInfoType,
  PhotosType,
  FeaturesType,
  DescriptionType,
  SocialType,
} from './edit_areas/types/types';

import { jamSchema } from './zodCheck';

type EditAreaProps = {
  childSaveOnUnmount: React.RefObject<() => void>;
};

export default function EditArea({ childSaveOnUnmount }: EditAreaProps) {
  const searchParams = useSearchParams();
  const currentSection = searchParams.get('section') || 'informaciongeneral';

  // One state per section
  const generalInfo = useRef<GeneralInfoType>({
    jam_title: '',
    location_title: '',
    location_address: '',
    coordinates: {
      lat: '',
      lng: '',
    },
    dates: {
      period: 'manual',
      day_of_week: null,
      time: { from: '21:30', to: null },
      list_of_dates: [],
    },
  });
  const photos = useRef<PhotosType>({ images: [] });
  const features = useRef<FeaturesType>({
    styles: [],
    song_list: false,
    intruments_lend: true,
    drums: true,
  });
  const description = useRef<DescriptionType>({
    description: null,
  });
  const social = useRef<SocialType>({
    instagram: '',
    facebook: '',
    siteWeb: '',
  });

  const uploadPhotos = async (files: File[]) => {
    const formData = new FormData();
    files.forEach((file) => formData.append('images', file));

    const res = await fetch('/api/upload-photos', {
      method: 'POST',
      body: formData,
    });

    const data = await res.json();
    return data.urls; // array of URLs generated by Supabase
  };

  const handleSave = async () => {
    childSaveOnUnmount.current?.();

    const images_files: File[] = [];
    for (const url of photos.current.images) {
      const res = await fetch(url);
      const blob = await res.blob();
      // optional: give a filename
      images_files.push(
        new File([blob], `image-${Date.now()}.png`, { type: blob.type }),
      );
    }

    const photos_urls = await uploadPhotos(images_files);
    console.log(generalInfo);
    const jamData = {
      jam_title: generalInfo.current.jam_title,
      location_title: generalInfo.current.location_title,
      location_address: generalInfo.current.location_address,
      periodicity: generalInfo.current.dates.period,
      dayOfWeek: generalInfo.current.dates.day_of_week,
      dates: generalInfo.current.dates.list_of_dates,
      time_start: generalInfo.current.dates.time.from,
      images: photos_urls,
      styles: features.current.styles,
      lista_canciones: features.current.song_list,

      instruments_lend: features.current.intruments_lend,
      drums: features.current.drums,
      description: description.current.description,
      social_links: social.current,
      location_coords: generalInfo.current.coordinates,
    };
    const parsed_jamData = jamSchema.safeParse(jamData);
    console.log(parsed_jamData);
    console.log('Saving all data:', jamData);

    const res = await fetch('/api/create-session', {
      method: 'POST',
      body: JSON.stringify(jamData),
      headers: { 'Content-Type': 'application/json' },
    });
    const data = await res.json();
  };

  return (
    <div>
      <div
        className="flex justify-center m-12 ml-auto p-2 bg-black text-white w-32 h-10 rounded-lg cursor-pointer 
  hover:text-black hover:bg-slate-200 hover:border hover:border-black"
        onClick={() => handleSave()}
      >
        Save and Exit
      </div>

      {currentSection === 'informaciongeneral' && (
        <GeneralInfo
          dataRef={generalInfo}
          childSaveOnUnmount={childSaveOnUnmount}
        />
      )}
      {currentSection === 'fotos' && (
        <UploadPhotos
          dataRef={photos}
          childSaveOnUnmount={childSaveOnUnmount}
        />
      )}
      {currentSection === 'caracteristicas' && (
        <PlaceChars
          dataRef={features}
          childSaveOnUnmount={childSaveOnUnmount}
        />
      )}
      {currentSection === 'descripcion' && (
        <PlaceDescription
          dataRef={description}
          childSaveOnUnmount={childSaveOnUnmount}
        />
      )}
      {currentSection === 'redessociales' && (
        <Social dataRef={social} childSaveOnUnmount={childSaveOnUnmount} />
      )}
    </div>
  );
}
