'use client';
import { useState, useRef, useEffect } from 'react';

import Sections from './sections';
import { useRouter } from 'next/navigation';

import { jamSchema } from './zodCheck';

import { useParams } from 'next/navigation';

import { useAtom } from 'jotai';
import { formAtom } from './store/jotai';

import { useFormStore } from './store/formStore'; // path a tu store

type EditAreaProps = {
  childSaveOnUnmount: React.RefObject<() => void>;
};

export default function EditArea({ childSaveOnUnmount }: EditAreaProps) {
  const setForm = useFormStore((state) => state.setForm);

  const router = useRouter(); // ✅ call hook here, at top level

  const [loading, setLoading] = useState(true);


  useEffect(() => {
    

 

        setForm({
     
          generalInfo: {
    jam_title: '',
    location_title: '',
    location_address: '',
    coordinates: {
      lat: '',
      lng: '',
    },
    dates: {
      period: 'manual',
      day_of_week: null,
      time: { from: '21:30', to: null },
      list_of_dates: [],
    },
  },
          photos: { images: [] },
          features:{
    styles: [],
    song_list: false,
    intruments_lend: true,
    drums: true,
  },
          description: { description: null },
          social:{
    instagram: '',
    facebook: '',
    siteWeb: '',
  },
        });

        setLoading(false);
      },[]);
// ✅ solo se ejecuta cuando cambia id

  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-

  const uploadPhotos = async (files: File[]) => {
    const formData = new FormData();
    files.forEach((file) => formData.append('images', file));

    const res = await fetch('/api/upload-photos', {
      method: 'POST',
      body: formData,
    });

    const data = await res.json();
    return data.urls; // array of URLs generated by Supabase
  };

  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-

  const handleSave = async () => {
    childSaveOnUnmount.current();

    const form = useFormStore.getState().form;

    console.log('YYYYYYYYYYYYYYYYYY');
    console.log('YYYYYYYYYYYYYYYYYY');
    console.log('YYYYYYYYYYYYYYYYYY');
    console.log('YYYYYYYYYYYYYYYYYY');
    console.log('YYYYYYYYYYYYYYYYYY');

    console.log(form);

    const images_files: File[] = [];
    for (const url of form.photos.images) {
      const res = await fetch(url);
      const blob = await res.blob();
      // optional: give a filename
      images_files.push(
        new File([blob], `image-${Date.now()}.png`, { type: blob.type }),
      );
    }

    const photos_urls = await uploadPhotos(images_files);
    console.log(form.generalInfo);
    const jamData = {
      jam_title: form.generalInfo.jam_title,
      location_title: form.generalInfo.location_title,
      location_address: form.generalInfo.location_address,
      periodicity: form.generalInfo.dates.period,
      dayOfWeek: form.generalInfo.dates.day_of_week,
      dates: form.generalInfo.dates.list_of_dates,
      time_start: form.generalInfo.dates.time.from,
      images: photos_urls,
      styles: form.features.styles,
      lista_canciones: form.features.song_list,

      instruments_lend: form.features.intruments_lend,
      drums: form.features.drums,
      description: form.description.description,
      social_links: form.social,
      location_coords: form.generalInfo.coordinates,
    };
    const parsed_jamData = jamSchema.safeParse(jamData);
    console.log(parsed_jamData);
    console.log('Saving all data:', jamData);

    const res = await fetch('/api/create-session', {
      method: 'POST',
      body: JSON.stringify(jamData),
      headers: { 'Content-Type': 'application/json' },
    });
    const data = await res.json();

    router.push(`/jams_list_signIn/`);
  };

  if (loading) return null;
  return (
    <div>
      <div
        className="flex justify-center m-12 ml-auto p-2 bg-black text-white w-32 h-10 rounded-lg cursor-pointer 
      hover:text-black hover:bg-slate-200 hover:border hover:border-black"
        onClick={() => handleSave()}
      >
        Save and Exit
      </div>

      <Sections childSaveOnUnmount={childSaveOnUnmount} />
    </div>
  );
}
