'use client';
import { useState, useRef, useEffect } from 'react';

import Sections from './sections';
import { useRouter } from 'next/navigation';

import { jamSchema } from './zodCheck';

import { useParams } from 'next/navigation';

import { useAtom } from 'jotai';
import { formAtom } from './store/jotai';

import { useFormStore } from './store/formStore'; // path a tu store

type EditAreaProps = {
  childSaveOnUnmount: React.RefObject<() => void>;
};

export default function EditArea({ childSaveOnUnmount }: EditAreaProps) {
  const setForm = useFormStore((state) => state.setForm);

  const router = useRouter(); // ✅ call hook here, at top level

  const [loading, setLoading] = useState(true);
  const { id } = useParams();

  useEffect(() => {
    if (!id) return;

    fetch(`/api/get-jam-edit/${id}`)
      .then((res) => res.json())
      .then((data) => {
        setForm({
          generalInfo: {
            jam_title: data.jam_title,
            location_title: data.location_title,
            location_address: data.location_address,
            coordinates: { lat: data.lat, lng: data.lng },
            dates: {
              period: data.periodicity,
              day_of_week: data.dayOfWeek,
              time: { from: data.time_start, to: null },
              list_of_dates: data.dates,
            },
          },
          photos: { images: data.images },
          features: {
            styles: data.styles,
            song_list: data.lista_canciones,
            intruments_lend: data.instruments_lend,
            drums: data.drums,
          },
          description: { description: data.description },
          social: {
            instagram: data.social_links.instagram,
            facebook: data.social_links.facebook,
            siteWeb: data.social_links.siteWeb,
          },
        });

        setLoading(false);
      });
  }, [id]); // ✅ solo se ejecuta cuando cambia id

  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-

  const uploadPhotos = async (files: File[]) => {
    const formData = new FormData();
    files.forEach((file) => formData.append('images', file));

    const res = await fetch('/api/upload-photos', {
      method: 'POST',
      body: formData,
    });

    const data = await res.json();
    return data.urls; // array of URLs generated by Supabase
  };

  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
  //#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-

  const handleSave = async () => {
    childSaveOnUnmount.current();

    const form = useFormStore.getState().form;

    const images_files: File[] = [];
    for (const url of form.photos.images) {
      const res = await fetch(url);
      const blob = await res.blob();
      // optional: give a filename
      images_files.push(
        new File([blob], `image-${Date.now()}.png`, { type: blob.type }),
      );
    }

    const photos_urls = await uploadPhotos(images_files);
    console.log(form.generalInfo);
    const jamData = {
      jam_title: form.generalInfo.jam_title,
      location_title: form.generalInfo.location_title,
      location_address: form.generalInfo.location_address,
      periodicity: form.generalInfo.dates.period,
      dayOfWeek: form.generalInfo.dates.day_of_week,
      dates: form.generalInfo.dates.list_of_dates,
      time_start: form.generalInfo.dates.time.from,
      images: photos_urls,
      styles: form.features.styles,
      lista_canciones: form.features.song_list,

      instruments_lend: form.features.intruments_lend,
      drums: form.features.drums,
      description: form.description.description,
      social_links: form.social,
      location_coords: form.generalInfo.coordinates,
    };
    const parsed_jamData = jamSchema.safeParse(jamData);
    console.log(parsed_jamData);
    console.log('Saving all data:', jamData);

    await fetch(`/api/update-session/${id}`, {
      method: 'POST',
      body: JSON.stringify(jamData),
      headers: { 'Content-Type': 'application/json' },
    });
  };

  const [progress, setProgress] = useState(0);
  const [saving, setSaving] = useState(false);

  if (loading) return null;
  return (
    <div className="relative">
      {saving ? (
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center gap-6 z-[501]">
          <ProgressDemo progress={progress} setProgress={setProgress} />
        </div>
      ) : null}
      <div
        className="flex justify-center m-12 ml-auto p-2 bg-black text-white w-32 h-10 rounded-lg cursor-pointer 
        hover:text-black hover:bg-slate-200 hover:border hover:border-black"
        onClick={async () => {
          setProgress(13);
          setSaving(true);

          // 1️⃣ helper to wait
          const wait = (ms: number) =>
            new Promise((resolve) => setTimeout(resolve, ms));

          // 2️⃣ run progress animation and save in parallel
          await Promise.all([
            (async () => {
              await wait(500);
              setProgress(33);
              await wait(1000);
              setProgress(66);
            })(),
            handleSave(),
          ]);
          await wait(200);
          setProgress(100);
          await wait(200);
          // 3️⃣ done, hide progress and navigate
          setSaving(false);
          router.push('/jams_list_signIn');
        }}
      >
        {saving ? 'Saving…' : 'Save and Exit'}
      </div>

      <Sections childSaveOnUnmount={childSaveOnUnmount} />
    </div>
  );
}

import { Progress } from '@/components/ui/progress';

export function ProgressDemo({ progress, setProgress }) {
  useEffect(() => {
    const timer = setTimeout(() => setProgress(66), 500);
    return () => clearTimeout(timer);
  }, []);

  return <Progress value={progress} className="w-64" />;
}
